### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by antgr** [WindChimeRan/pytorch_multi_head_selection_re#4]
In google colab environment

!python main.py --mode train --exp_name conll_selection_re
gives the following error

Traceback (most recent call last):
  File "main.py", line 146, in <module>
    config.run(mode=args.mode)
  File "main.py", line 76, in run
    self._init_model()
  File "main.py", line 57, in _init_model
    self.model = MultiHeadSelection(self.hyper).cuda(self.gpu)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: invalid device ordinal

**Comment by WindChimeRan** [comment]
You only have one GPU in colab. Thus, set device gpu=0.

Please see my config file:

https://github.com/WindChimeRan/pytorch_multi_head_selection_re/blob/master/experiments/conll_selection_re.json#L23

**Comment by antgr** [comment]
Thank you!
